// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: protobuf/dapplink-wallet.proto

package dal_wallet_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReturnCode int32

const (
	ReturnCode_ERROR   ReturnCode = 0
	ReturnCode_SUCCESS ReturnCode = 1
)

// Enum value maps for ReturnCode.
var (
	ReturnCode_name = map[int32]string{
		0: "ERROR",
		1: "SUCCESS",
	}
	ReturnCode_value = map[string]int32{
		"ERROR":   0,
		"SUCCESS": 1,
	}
)

func (x ReturnCode) Enum() *ReturnCode {
	p := new(ReturnCode)
	*p = x
	return p
}

func (x ReturnCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReturnCode) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_dapplink_wallet_proto_enumTypes[0].Descriptor()
}

func (ReturnCode) Type() protoreflect.EnumType {
	return &file_protobuf_dapplink_wallet_proto_enumTypes[0]
}

func (x ReturnCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReturnCode.Descriptor instead.
func (ReturnCode) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{0}
}

// 样板Response
type BoilerplateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code ReturnCode `protobuf:"varint,1,opt,name=Code,proto3,enum=syncs.ReturnCode" json:"Code,omitempty"`
	Msg  string     `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *BoilerplateResponse) Reset() {
	*x = BoilerplateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_dapplink_wallet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoilerplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoilerplateResponse) ProtoMessage() {}

func (x *BoilerplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoilerplateResponse.ProtoReflect.Descriptor instead.
func (*BoilerplateResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *BoilerplateResponse) GetCode() ReturnCode {
	if x != nil {
		return x.Code
	}
	return ReturnCode_ERROR
}

func (x *BoilerplateResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 注册扫链服务参数
type SignUpScanServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户唯一标识
	RequestId string `protobuf:"bytes,1,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
}

func (x *SignUpScanServiceRequest) Reset() {
	*x = SignUpScanServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_dapplink_wallet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignUpScanServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpScanServiceRequest) ProtoMessage() {}

func (x *SignUpScanServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpScanServiceRequest.ProtoReflect.Descriptor instead.
func (*SignUpScanServiceRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *SignUpScanServiceRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// 地址类型
type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 0:用户地址；1:热钱包地址(归集地址)；2:冷钱包地址
	AddressType uint32 `protobuf:"varint,1,opt,name=AddressType,proto3" json:"AddressType,omitempty"`
	// 地址
	Address string `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_dapplink_wallet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *Address) GetAddressType() uint32 {
	if x != nil {
		return x.AddressType
	}
	return 0
}

func (x *Address) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// 设置扫链地址
type SetScanAddressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId   string     `protobuf:"bytes,1,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
	AddressList []*Address `protobuf:"bytes,2,rep,name=AddressList,proto3" json:"AddressList,omitempty"`
}

func (x *SetScanAddressRequest) Reset() {
	*x = SetScanAddressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_dapplink_wallet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetScanAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetScanAddressRequest) ProtoMessage() {}

func (x *SetScanAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetScanAddressRequest.ProtoReflect.Descriptor instead.
func (*SetScanAddressRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *SetScanAddressRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SetScanAddressRequest) GetAddressList() []*Address {
	if x != nil {
		return x.AddressList
	}
	return nil
}

type RefreshCacheRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string `protobuf:"bytes,1,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
}

func (x *RefreshCacheRequest) Reset() {
	*x = RefreshCacheRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_dapplink_wallet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshCacheRequest) ProtoMessage() {}

func (x *RefreshCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshCacheRequest.ProtoReflect.Descriptor instead.
func (*RefreshCacheRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshCacheRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type Token struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Decimals        uint32 `protobuf:"varint,1,opt,name=Decimals,proto3" json:"Decimals,omitempty"`
	Address         string `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	TokenName       string `protobuf:"bytes,3,opt,name=TokenName,proto3" json:"TokenName,omitempty"`
	CollectionLimit uint64 `protobuf:"varint,4,opt,name=CollectionLimit,proto3" json:"CollectionLimit,omitempty"`
}

func (x *Token) Reset() {
	*x = Token{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_dapplink_wallet_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *Token) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *Token) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Token) GetTokenName() string {
	if x != nil {
		return x.TokenName
	}
	return ""
}

func (x *Token) GetCollectionLimit() uint64 {
	if x != nil {
		return x.CollectionLimit
	}
	return 0
}

type SetTokenAddressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenList []*Token `protobuf:"bytes,1,rep,name=TokenList,proto3" json:"TokenList,omitempty"`
}

func (x *SetTokenAddressRequest) Reset() {
	*x = SetTokenAddressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_dapplink_wallet_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTokenAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTokenAddressRequest) ProtoMessage() {}

func (x *SetTokenAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_dapplink_wallet_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTokenAddressRequest.ProtoReflect.Descriptor instead.
func (*SetTokenAddressRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_dapplink_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *SetTokenAddressRequest) GetTokenList() []*Token {
	if x != nil {
		return x.TokenList
	}
	return nil
}

var File_protobuf_dapplink_wallet_proto protoreflect.FileDescriptor

var file_protobuf_dapplink_wallet_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x61, 0x70, 0x70, 0x6c,
	0x69, 0x6e, 0x6b, 0x2d, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x73, 0x79, 0x6e, 0x63, 0x73, 0x22, 0x4e, 0x0a, 0x13, 0x42, 0x6f, 0x69, 0x6c, 0x65,
	0x72, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25,
	0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x73,
	0x79, 0x6e, 0x63, 0x73, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x38, 0x0a, 0x18, 0x53, 0x69, 0x67, 0x6e, 0x55,
	0x70, 0x53, 0x63, 0x61, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x22, 0x45, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x20, 0x0a, 0x0b,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0b, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x67, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x53,
	0x63, 0x61, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12,
	0x30, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x73, 0x2e, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x52, 0x0b, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x33, 0x0a, 0x13, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x22, 0x85, 0x01, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x1a, 0x0a, 0x08, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x43,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x44,
	0x0a, 0x16, 0x53, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x09, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x79,
	0x6e, 0x63, 0x73, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x09, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x4c, 0x69, 0x73, 0x74, 0x2a, 0x24, 0x0a, 0x0a, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x32, 0xcb, 0x02, 0x0a, 0x09, 0x53,
	0x63, 0x61, 0x6e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x52, 0x0a, 0x11, 0x53, 0x69, 0x67, 0x6e,
	0x55, 0x70, 0x53, 0x63, 0x61, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1f, 0x2e,
	0x73, 0x79, 0x6e, 0x63, 0x73, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x53, 0x63, 0x61, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x73, 0x79, 0x6e, 0x63, 0x73, 0x2e, 0x42, 0x6f, 0x69, 0x6c, 0x65, 0x72, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x0e,
	0x53, 0x65, 0x74, 0x53, 0x63, 0x61, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1c,
	0x2e, 0x73, 0x79, 0x6e, 0x63, 0x73, 0x2e, 0x53, 0x65, 0x74, 0x53, 0x63, 0x61, 0x6e, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73,
	0x79, 0x6e, 0x63, 0x73, 0x2e, 0x42, 0x6f, 0x69, 0x6c, 0x65, 0x72, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x12, 0x48, 0x0a, 0x0c,
	0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12, 0x1a, 0x2e, 0x73,
	0x79, 0x6e, 0x63, 0x73, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x73,
	0x2e, 0x42, 0x6f, 0x69, 0x6c, 0x65, 0x72, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1d, 0x2e, 0x73, 0x79, 0x6e, 0x63,
	0x73, 0x2e, 0x53, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x73,
	0x2e, 0x42, 0x6f, 0x69, 0x6c, 0x65, 0x72, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x42, 0x1a, 0x5a, 0x18, 0x2e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x61, 0x6c, 0x2d, 0x77, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x2d, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_dapplink_wallet_proto_rawDescOnce sync.Once
	file_protobuf_dapplink_wallet_proto_rawDescData = file_protobuf_dapplink_wallet_proto_rawDesc
)

func file_protobuf_dapplink_wallet_proto_rawDescGZIP() []byte {
	file_protobuf_dapplink_wallet_proto_rawDescOnce.Do(func() {
		file_protobuf_dapplink_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_dapplink_wallet_proto_rawDescData)
	})
	return file_protobuf_dapplink_wallet_proto_rawDescData
}

var file_protobuf_dapplink_wallet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_dapplink_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protobuf_dapplink_wallet_proto_goTypes = []any{
	(ReturnCode)(0),                  // 0: syncs.ReturnCode
	(*BoilerplateResponse)(nil),      // 1: syncs.BoilerplateResponse
	(*SignUpScanServiceRequest)(nil), // 2: syncs.SignUpScanServiceRequest
	(*Address)(nil),                  // 3: syncs.Address
	(*SetScanAddressRequest)(nil),    // 4: syncs.SetScanAddressRequest
	(*RefreshCacheRequest)(nil),      // 5: syncs.RefreshCacheRequest
	(*Token)(nil),                    // 6: syncs.Token
	(*SetTokenAddressRequest)(nil),   // 7: syncs.SetTokenAddressRequest
}
var file_protobuf_dapplink_wallet_proto_depIdxs = []int32{
	0, // 0: syncs.BoilerplateResponse.Code:type_name -> syncs.ReturnCode
	3, // 1: syncs.SetScanAddressRequest.AddressList:type_name -> syncs.Address
	6, // 2: syncs.SetTokenAddressRequest.TokenList:type_name -> syncs.Token
	2, // 3: syncs.ScanChain.SignUpScanService:input_type -> syncs.SignUpScanServiceRequest
	4, // 4: syncs.ScanChain.SetScanAddress:input_type -> syncs.SetScanAddressRequest
	5, // 5: syncs.ScanChain.RefreshCache:input_type -> syncs.RefreshCacheRequest
	7, // 6: syncs.ScanChain.SetTokenAddress:input_type -> syncs.SetTokenAddressRequest
	1, // 7: syncs.ScanChain.SignUpScanService:output_type -> syncs.BoilerplateResponse
	1, // 8: syncs.ScanChain.SetScanAddress:output_type -> syncs.BoilerplateResponse
	1, // 9: syncs.ScanChain.RefreshCache:output_type -> syncs.BoilerplateResponse
	1, // 10: syncs.ScanChain.SetTokenAddress:output_type -> syncs.BoilerplateResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protobuf_dapplink_wallet_proto_init() }
func file_protobuf_dapplink_wallet_proto_init() {
	if File_protobuf_dapplink_wallet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_dapplink_wallet_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*BoilerplateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_dapplink_wallet_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SignUpScanServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_dapplink_wallet_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_dapplink_wallet_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SetScanAddressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_dapplink_wallet_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*RefreshCacheRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_dapplink_wallet_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Token); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_dapplink_wallet_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*SetTokenAddressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_dapplink_wallet_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_dapplink_wallet_proto_goTypes,
		DependencyIndexes: file_protobuf_dapplink_wallet_proto_depIdxs,
		EnumInfos:         file_protobuf_dapplink_wallet_proto_enumTypes,
		MessageInfos:      file_protobuf_dapplink_wallet_proto_msgTypes,
	}.Build()
	File_protobuf_dapplink_wallet_proto = out.File
	file_protobuf_dapplink_wallet_proto_rawDesc = nil
	file_protobuf_dapplink_wallet_proto_goTypes = nil
	file_protobuf_dapplink_wallet_proto_depIdxs = nil
}
